package bloodbank;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;

public class AlertManager {
    private int lowStockThreshold;
    private int expiryAlertDays;

    public AlertManager(int lowStockThreshold, int expiryAlertDays) {
        this.lowStockThreshold = lowStockThreshold;
        this.expiryAlertDays = expiryAlertDays;
    }

    public AlertManager() {
        this.lowStockThreshold = 10;
        this.expiryAlertDays = 7;
    }

    public int getLowStockThreshold() { return lowStockThreshold; }
    public void setLowStockThreshold(int lowStockThreshold) { this.lowStockThreshold = lowStockThreshold; }

    public int getExpiryAlertDays() { return expiryAlertDays; }
    public void setExpiryAlertDays(int expiryAlertDays) { this.expiryAlertDays = expiryAlertDays; }

    public void checkLowStock(Inventory inventory) {
        String[] groups = {"A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"};
        boolean lowStockFound = false;
        System.out.println("\n[ALERT MANAGER] Running Low Stock Level Check (Threshold: " + lowStockThreshold + " units)...");
        for (String g : groups) {
            int stock = inventory.getStockForGroup(g);
            if (stock < lowStockThreshold) {
                System.out.println("  >> LOW STOCK ALERT: Blood Group " + g + " has only " + stock + " units available!");
                lowStockFound = true;
            }
        }
        if (!lowStockFound) {
            System.out.println("  >> All blood groups have adequate stock levels.");
        }
    }

    public void checkLowStock() {
        System.out.println("Checking low stock...");
    }

    public void checkExpiry(Inventory inventory) {
        System.out.println("\n[ALERT MANAGER] Running Expiration Check (Threshold: " + expiryAlertDays + " days)...");
        LocalDate now = LocalDate.now();
        boolean issuesFound = false;
        
        for (BloodUnit bu : inventory.getBloodUnits()) {
            if (bu.isExpired()) {
                System.out.println("  >> EXPIRED ALERT: Blood Unit " + bu.getBloodUnitId() + " [" + bu.getBloodGroup() + 
                                   "] expired on " + bu.getExpiryDate() + "!");
                issuesFound = true;
            } else {
                try {
                    LocalDate exp = LocalDate.parse(bu.getExpiryDate());
                    long daysBetween = ChronoUnit.DAYS.between(now, exp);
                    if (daysBetween <= expiryAlertDays) {
                        System.out.println("  >> NEAR EXPIRY WARNING: Blood Unit " + bu.getBloodUnitId() + " [" + bu.getBloodGroup() + 
                                           "] will expire in " + daysBetween + " days (Date: " + bu.getExpiryDate() + ")!");
                        issuesFound = true;
                    }
                } catch (DateTimeParseException e) {
                    // Ignore malformed dates during bulk check
                }
            }
        }
        if (!issuesFound) {
            System.out.println("  >> No expired or near-expiry blood units detected.");
        }
    }

    public void checkExpiry() {
        System.out.println("Checking expiry...");
    }

    public void generateAlert() {
        System.out.println("[ALERT] General alert generated by system.");
    }
}
